---
- hosts: all
  become: yes
  strategy: debug
  any_errors_fatal: true
  #no_log: true
  #gather_facts: True
  #gather_subset: hardware
  roles:
    - { role: confbase }
    - { role: ntp }
    - { role: zabbix }
    - { role: confdev, IP_SRV_SAMBA: ipdev , DEVS: devname, diretorio: /home/dirdev/   }
    - { role: hardening, ansible_hostname: hostname } 
    - { role: bacula }
    - { role: docker-host, mount_point: /mountpoint, mount_path: /mountpath }
   

  

  
