---
- name:  Configurar Docker no Centos 
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
  shell: curl -fsSL https://get.docker.com/ | sh

- name:  Instalando GPG key no Ubuntu 
  when: ansible_distribution_version == "18.04" or ansible_distribution_version == "16.04" 
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  register: GPG_key 

- name: Instalando repositório no Ubuntu
  when: ansible_distribution_version == "18.04"   
  apt_repository:
    repo: deb  [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
  register: add_repo

- name: Instalando repositório no Ubuntu
  when: ansible_distribution_version == "16.04"  
  apt_repository:
    repo: deb  [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
  register: add_repo

- name: Atualizando apt
  when: ansible_distribution_version == "18.04" or ansible_distribution_version == "16.04" and GPG_key  is succeeded and add_repo is succeeded
  apt: 
    update_cache: yes

- name: Instalação de pacotes basicos Ubuntu
  when: ansible_distribution_version == "18.04" or ansible_distribution_version == "16.04"
  apt:
    name:  docker-ce
    state: present
    update_cache: true
  notify: 
    - Restart docker

- name:  Configure docker-compose 
  shell: 
    cmd: |
      curl -L https://github.com/docker/compose/releases/download/{{ release }}/docker-compose-`uname -s`-`uname -m` -o /usr/bin/docker-compose 
      chmod +x /usr/bin/docker-compose
      docker-compose --version
      exit 0
  args:
   warn: False
         

        